version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: backend
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    container_name: worker
    command: celery -A tasks.app worker --loglevel=info --concurrency=1
    depends_on:
      - redis
      - backend
  web:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - PORT=8001
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: python Deploy.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 